name: Generate and publish

on:
  workflow_dispatch:
  schedule:
    - cron: "0 4 * * *"

env:
  LEVERADE_USER_ID: ${{ secrets.LEVERADE_USER_ID }}
  LEVERADE_USER_EMAIL: ${{ secrets.LEVERADE_USER_EMAIL }}
  LEVERADE_USER_PASSWORD: ${{ secrets.LEVERADE_USER_PASSWORD }}
  LEVERADE_CLIENT_ID: ${{ secrets.LEVERADE_CLIENT_ID }}
  LEVERADE_CLIENT_SECRET: ${{ secrets.LEVERADE_CLIENT_SECRET }}
  REFEREES_DATA_FILEPATH: "./referees.csv"
  REFEREES_PUBLIC_DATA_FILEPATH: "./referees_public.json"

jobs:
  Generate-and-publish-lists:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout üõé
        uses: actions/checkout@master

      - name: Setup node env üèó
        uses: actions/setup-node@v4.2.0
        with:
          node-version: 22
          check-latest: true

      - name: Cache node_modules üì¶
        uses: actions/cache@v4.2.2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies üë®üèª‚Äçüíª
        run: npm ci --prefer-offline --no-audit

      - name: Generate referee lists üìÑ
        run: npm start

      - name: Copy public list to server
        uses: garygrossgarten/github-action-scp@v0.9.0
        with:
          local: referees_public.json
          remote: files/arbitrage/liste-arbitres/referees_public.json
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}

      - name: Copy private list to server
        uses: garygrossgarten/github-action-scp@v0.9.0
        with:
          local: referees.csv
          remote: files/arbitrage/liste-arbitres/privee/referees.csv
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
